INSERT INTO operator VALUES ('12F', 0, 'Clue Search Beta');
INSERT INTO operator VALUES ('12F', 1, 'Training Record');
INSERT INTO operator VALUES ('Adnachiel', 0, 'Order Distribution Alpha');
INSERT INTO operator VALUES ('Adnachiel', 1, 'Skillful Craftsman');
INSERT INTO operator VALUES ('Amiya', 0, 'Agreement');
INSERT INTO operator VALUES ('Amiya', 2, 'Violin Solo');
INSERT INTO operator VALUES ('Angelina', 0, 'Clue Search Alpha');
INSERT INTO operator VALUES ('Angelina', 2, 'Messenger');
INSERT INTO operator VALUES ('Ansel', 0, 'Thoughtfulness');
INSERT INTO operator VALUES ('Ansel', 1, 'Pharmacology Alpha');
INSERT INTO operator VALUES ('Astesia', 0, 'Clue Search Alpha');
INSERT INTO operator VALUES ('Astesia', 1, 'Astrology');
INSERT INTO operator VALUES ('Beagle', 0, 'Warehouse Organization Alpha');
INSERT INTO operator VALUES ('Beagle', 1, 'Liveliness');
INSERT INTO operator VALUES ('Beehunter', 0, 'Guard Expert Alpha');
INSERT INTO operator VALUES ('Beehunter', 1, 'Training Record');
INSERT INTO operator VALUES ('Blue Poison', 0, 'Toxicology Alpha');
INSERT INTO operator VALUES ('Blue Poison', 2, 'Toxicology Beta');
INSERT INTO operator VALUES ('Castle-3', 0, 'Backup Energy');
INSERT INTO operator VALUES ('Castle-3', 1, 'Combat Guidance Video');
INSERT INTO operator VALUES ('Cardigan', 0, 'Warehouse Organization Alpha');
INSERT INTO operator VALUES ('Cardigan', 1, 'Liveliness');
INSERT INTO operator VALUES ('Catapult', 0, 'Communication');
INSERT INTO operator VALUES ('Catapult', 1, 'Blasting Materialogy Beta');
INSERT INTO operator VALUES (E'Ch\'en', 0, 'Integrity & Capability');
INSERT INTO operator VALUES (E'Ch\'en', 2, 'Police Superintendent');
INSERT INTO operator VALUES ('Cliffheart', 0, E'Explorer\'s Passion');
INSERT INTO operator VALUES ('Cliffheart', 2, 'Karlan Commercial Beta');
INSERT INTO operator VALUES ('Courier', 0, 'Karlan Commercial Alpha');
INSERT INTO operator VALUES ('Courier', 1, 'Courier');
INSERT INTO operator VALUES ('Croissant', 0, 'Penguin Logistics Alpha');
INSERT INTO operator VALUES ('Croissant', 2, 'Mission Guarantee');
INSERT INTO operator VALUES ('Cuora', 0, 'Warehouse Organization Beta');
INSERT INTO operator VALUES ('Cuora', 1, 'Order Distribution Alpha');
INSERT INTO operator VALUES ('Deepcolor', 0, 'Order Distribution Alpha');
INSERT INTO operator VALUES ('Deepcolor', 1, 'Focus Beta');
INSERT INTO operator VALUES ('Dobermann', 0, 'Capable Assistance');
INSERT INTO operator VALUES ('Dobermann', 1, 'Drillmaster');
INSERT INTO operator VALUES ('Durin', 0, 'Laziness');
INSERT INTO operator VALUES ('Durin', 1, 'Sleepiness');
INSERT INTO operator VALUES ('Earthspirit', 0, 'Catastrophe Messenger Alpha');
INSERT INTO operator VALUES ('Earthspirit', 1, 'Catastrophe Messenger Alpha');
INSERT INTO operator VALUES ('Estelle', 0, 'Focus Beta');
INSERT INTO operator VALUES ('Estelle', 1, 'Solitude');
INSERT INTO operator VALUES ('Executor', 0, 'Sniper Expert Alpha');
INSERT INTO operator VALUES ('Executor', 2, 'Cleaning Agreement');
INSERT INTO operator VALUES ('Exusiai', 0, 'Penguin Logistics Alpha');
INSERT INTO operator VALUES ('Exusiai', 2, 'Logistics Expert');
INSERT INTO operator VALUES ('Eyjafjalla', 0, 'Volcanologist');
INSERT INTO operator VALUES ('Eyjafjalla', 2, 'Catastrophe Messenger Beta');
INSERT INTO operator VALUES ('FEater', 0, 'Combat Guidance Video');
INSERT INTO operator VALUES ('FEater', 2, 'Boxing Guidance Video');
INSERT INTO operator VALUES ('Fang', 0, 'Hothead');
INSERT INTO operator VALUES ('Fang', 1, 'Order Distribution Beta');
INSERT INTO operator VALUES ('Firewatch', 0, 'Clue Search Alpha');
INSERT INTO operator VALUES ('Firewatch', 2, 'Clue Search Beta');
INSERT INTO operator VALUES ('Flamebringer', 0, 'Tech Theory');
INSERT INTO operator VALUES ('Flamebringer', 2, 'Arise');
INSERT INTO operator VALUES ('Franka', 0, 'Guard Expert Alpha');
INSERT INTO operator VALUES ('Franka', 2, 'Guard Expert Beta');
INSERT INTO operator VALUES ('Frostleaf', 0, 'Solitude');
INSERT INTO operator VALUES ('Frostleaf', 1, 'Combat Guidance Video');
INSERT INTO operator VALUES ('Gavial', 0, 'Pharmacology Alpha');
INSERT INTO operator VALUES ('Gavial', 1, 'Medic Expert Alpha');
INSERT INTO operator VALUES ('Gitano', 0, 'Supply Management');
INSERT INTO operator VALUES ('Gitano', 1, 'Divination');
INSERT INTO operator VALUES ('Grani', 0, 'Vanguard Expert Alpha');
INSERT INTO operator VALUES ('Grani', 2, 'Vanguard Expert Beta');
INSERT INTO operator VALUES ('Gravel', 0, 'Focus Alpha');
INSERT INTO operator VALUES ('Gravel', 1, 'Metalwork Beta');
INSERT INTO operator VALUES ('Greyy', 0, 'Electrostatic Field');
INSERT INTO operator VALUES ('Greyy', 1, 'Skillful Craftsman');
INSERT INTO operator VALUES ('Gummy', 0, 'Communication');
INSERT INTO operator VALUES ('Gummy', 1, 'Cooking');
INSERT INTO operator VALUES ('Haze', 0, 'Metalwork Alpha');
INSERT INTO operator VALUES ('Haze', 1, 'Order Distribution Beta');
INSERT INTO operator VALUES ('Hellagur', 0, 'Release');
INSERT INTO operator VALUES ('Hellagur', 0, 'Arts of War');
INSERT INTO operator VALUES ('Hellagur', 1, 'Break Loose');
INSERT INTO operator VALUES ('Hellagur', 2, 'Absolution');
INSERT INTO operator VALUES ('Hibiscus', 0, 'Thoughtfulness');
INSERT INTO operator VALUES ('Hibiscus', 1, 'Nutriology');
INSERT INTO operator VALUES ('Hoshiguma', 0, 'Defender Expert Alpha');
INSERT INTO operator VALUES ('Hoshiguma', 2, 'Hannya');
INSERT INTO operator VALUES ('Ifrit', 0, 'Heat Charge Alpha');
INSERT INTO operator VALUES ('Ifrit', 2, 'Superheat Charge');
INSERT INTO operator VALUES ('Indra', 0, 'Clue Search Alpha');
INSERT INTO operator VALUES ('Indra', 2, 'Arraigner');
INSERT INTO operator VALUES ('Istina', 0, 'Supporter Expert Alpha');
INSERT INTO operator VALUES ('Istina', 2, 'Counselor');
INSERT INTO operator VALUES ('Jessica', 0, 'Standardization Beta');
INSERT INTO operator VALUES ('Jessica', 1, 'Liaison');
INSERT INTO operator VALUES ('Kroos', 0, 'Slowcoach');
INSERT INTO operator VALUES ('Kroos', 1, 'Solitude');
INSERT INTO operator VALUES ('Lancet-2', 0, 'Backup Energy');
INSERT INTO operator VALUES ('Lancet-2', 1, 'Medical Service');
INSERT INTO operator VALUES ('Lappland', 0, 'Hidden Purpose Alpha');
INSERT INTO operator VALUES ('Lappland', 2, 'Hidden Purpose Beta');
INSERT INTO operator VALUES ('Lava', 0, 'Heat Charge Alpha');
INSERT INTO operator VALUES ('Lava', 1, 'Originium Work Beta');
INSERT INTO operator VALUES ('Liskarm', 0, 'Pulsed Arc Alpha');
INSERT INTO operator VALUES ('Liskarm', 2, 'Pulsed Arc Beta');
INSERT INTO operator VALUES ('Nearl', 0, 'Capable Assistance');
INSERT INTO operator VALUES ('Nearl', 2, 'Radiant Knight');
INSERT INTO operator VALUES ('Nightingale', 0, 'Inspiration');
INSERT INTO operator VALUES ('Nightingale', 2, 'Lady of the Lamp');
INSERT INTO operator VALUES ('Nightmare', 0, 'Caster Expert Alpha');
INSERT INTO operator VALUES ('Nightmare', 2, 'Psychology');
INSERT INTO operator VALUES ('Magallan', 0, 'Multifunctional Robotter');
INSERT INTO operator VALUES ('Magallan', 2, 'Drone - Soaring Dragon');
INSERT INTO operator VALUES ('Manticore', 0, 'Specialist Expert Alpha');
INSERT INTO operator VALUES ('Manticore', 2, 'Specialist Expert Beta');
INSERT INTO operator VALUES ('Matoimaru', 0, 'Tech Theory');
INSERT INTO operator VALUES ('Matoimaru', 1, 'Order Distribution Beta');
INSERT INTO operator VALUES ('Matterhorn', 0, 'Karlan Commercial Alpha');
INSERT INTO operator VALUES ('Matterhorn', 1, 'Defender Expert Beta');
INSERT INTO operator VALUES ('Mayer', 0, 'Meeboo: Processing');
INSERT INTO operator VALUES ('Mayer', 2, 'Meeboo: Manufacturing');
INSERT INTO operator VALUES ('Melantha', 0, 'Supply Management');
INSERT INTO operator VALUES ('Melantha', 1, 'Focus Alpha');
INSERT INTO operator VALUES ('Meteor', 0, 'Standardization Alpha');
INSERT INTO operator VALUES ('Meteor', 1, 'Thoughtfulness');
INSERT INTO operator VALUES ('Meteorite', 0, 'Blasting Materialogy Alpha');
INSERT INTO operator VALUES ('Meteorite', 2, 'Blasting Materialogy Beta');
INSERT INTO operator VALUES ('Midnight', 0, 'Communication');
INSERT INTO operator VALUES ('Midnight', 1, 'Originium Work Alpha');
INSERT INTO operator VALUES ('Mousse', 0, 'Order Distribution Beta');
INSERT INTO operator VALUES ('Mousse', 1, 'Baking');
INSERT INTO operator VALUES ('Myrrh', 0, 'Pharmacology Alpha');
INSERT INTO operator VALUES ('Myrrh', 1, 'Thoughtfulness');
INSERT INTO operator VALUES ('Noir Corne', 0, 'Warehouse Organization Beta');
INSERT INTO operator VALUES ('Noir Corne', 1, 'Order Management Alpha');
INSERT INTO operator VALUES ('Orchid', 0, 'Psychology');
INSERT INTO operator VALUES ('Orchid', 1, 'Supply Management');
INSERT INTO operator VALUES ('Perfumer', 0, 'Pharmacology Alpha');
INSERT INTO operator VALUES ('Perfumer', 1, 'Standardization Beta');
INSERT INTO operator VALUES ('Platinum', 0, 'Sniper Expert Alpha');
INSERT INTO operator VALUES ('Platinum', 2, 'Sniper Expert Beta');
INSERT INTO operator VALUES ('Plume', 0, 'Vanguard Expert Alpha');
INSERT INTO operator VALUES ('Plume', 1, 'Order Management Alpha');
INSERT INTO operator VALUES ('Popukar', 0, 'Troublemaker');
INSERT INTO operator VALUES ('Popukar', 1, 'Harmonious');
INSERT INTO operator VALUES ('Pramanix', 0, 'Karlan Saint');
INSERT INTO operator VALUES ('Pramanix', 2, 'Supporter Expert Beta');
INSERT INTO operator VALUES ('Projekt Red', 0, 'S.W.E.E.P.');
INSERT INTO operator VALUES ('Projekt Red', 2, 'Tracker');
INSERT INTO operator VALUES ('Provence', 0, 'Catastrophe Messenger Alpha');
INSERT INTO operator VALUES ('Provence', 2, 'Catastrophe Messenger Beta');
INSERT INTO operator VALUES ('Ptilopsis', 0, 'Rhine Tech Alpha');
INSERT INTO operator VALUES ('Ptilopsis', 2, 'Rhine Tech Beta');
INSERT INTO operator VALUES ('Rangers', 0, 'Personnel Management Alpha');
INSERT INTO operator VALUES ('Rangers', 1, 'Skillful Craftsman');
INSERT INTO operator VALUES ('Rope', 0, 'Clue Search Beta');
INSERT INTO operator VALUES ('Rope', 1, 'Negotiation');
INSERT INTO operator VALUES ('Saria', 0, 'Clue Search Alpha');
INSERT INTO operator VALUES ('Saria', 2, 'Watchman');
INSERT INTO operator VALUES ('Savage', 0, 'Tech Theory');
INSERT INTO operator VALUES ('Savage', 2, 'Cooking');
INSERT INTO operator VALUES ('Scavenger', 0, 'S.W.E.E.P.');
INSERT INTO operator VALUES ('Scavenger', 1, 'Junkman');
INSERT INTO operator VALUES ('Shaw', 0, 'Engineering');
INSERT INTO operator VALUES ('Shaw', 1, 'Equipment Maintenance');
INSERT INTO operator VALUES ('Shining', 0, 'Thoughtfulness');
INSERT INTO operator VALUES ('Shining', 2, 'Mercy');
INSERT INTO operator VALUES ('Shirayuki', 0, 'Clue Search Beta');
INSERT INTO operator VALUES ('Shirayuki', 1, 'Combat Guidance Video');
INSERT INTO operator VALUES ('Siege', 0, 'Leader');
INSERT INTO operator VALUES ('Siege', 2, 'Lionheart');
INSERT INTO operator VALUES ('Silence', 0, 'Rhine Tech Alpha');
INSERT INTO operator VALUES ('Silence', 2, 'Rhine Tech Beta');
INSERT INTO operator VALUES ('SilverAsh', 0, 'Karlan Commercial Alpha');
INSERT INTO operator VALUES ('SilverAsh', 2, 'Lord of Karlan');
INSERT INTO operator VALUES ('Skadi', 0, 'Solitude');
INSERT INTO operator VALUES ('Skadi', 2, 'Elegy');
INSERT INTO operator VALUES ('Skyfire', 0, 'Caster Expert Alpha');
INSERT INTO operator VALUES ('Skyfire', 2, 'Caster Expert Beta');
INSERT INTO operator VALUES ('Sora', 0, 'Idol');
INSERT INTO operator VALUES ('Sora', 2, 'Penguin Logistics Beta');
INSERT INTO operator VALUES ('Specter', 0, 'Solitude');
INSERT INTO operator VALUES ('Specter', 2, 'Craze');
INSERT INTO operator VALUES ('Spot', 0, 'Skillful Craftsman');
INSERT INTO operator VALUES ('Spot', 1, 'Metalwork Alpha');
INSERT INTO operator VALUES ('Steward', 0, 'Negotiation');
INSERT INTO operator VALUES ('Steward', 1, 'Standardization Beta');
INSERT INTO operator VALUES ('Swire', 0, 'Princess');
INSERT INTO operator VALUES ('Swire', 2, 'Drillmaster');
INSERT INTO operator VALUES ('Texas', 0, 'Feud');
INSERT INTO operator VALUES ('Texas', 2, 'Tacit Understanding');
INSERT INTO operator VALUES ('Vanilla', 0, 'Standardization Beta');
INSERT INTO operator VALUES ('Vanilla', 1, 'Order Distribution Alpha');
INSERT INTO operator VALUES ('Vermeil', 0, 'Junkman');
INSERT INTO operator VALUES ('Vermeil', 1, 'Recycling');
INSERT INTO operator VALUES ('Vigna', 0, 'Combat Guidance Video');
INSERT INTO operator VALUES ('Vigna', 1, 'Vanguard Expert Beta');
INSERT INTO operator VALUES ('Vulcan', 0, 'Craftsmanship Spirit Alpha');
INSERT INTO operator VALUES ('Vulcan', 2, 'Craftsmanship Spirit Beta');
INSERT INTO operator VALUES ('Warfarin', 0, 'Medic Expert Alpha');
INSERT INTO operator VALUES ('Warfarin', 2, 'Medic Expert Beta');
INSERT INTO operator VALUES ('Yato', 0, 'Order Distribution Beta');
INSERT INTO operator VALUES ('Yato', 1, 'Standardization Alpha');
INSERT INTO operator VALUES ('Zima', 0, 'Leader');
INSERT INTO operator VALUES ('Zima', 2, 'General Zima');