INSERT INTO skill (skill_name, skill_type, all_morale, efficiency) VALUES ('Capable Assistance', 'hq', -0.05, 0);
INSERT INTO skill (skill_name, skill_type, all_morale, efficiency) VALUES ('Cleaning Agreement', 'hq', -0.05, 0);
INSERT INTO skill (skill_name, skill_type, all_morale, efficiency) VALUES ('S.W.E.E.P.', 'hq', -0.05, 0);
INSERT INTO skill (skill_name, skill_type, all_morale, efficiency) VALUES ('Snack Network', 'hq', -0.05, 0);
INSERT INTO skill (skill_name, skill_type, all_morale, efficiency, notes) VALUES ('Agreement', 'hq', 0, 7, 'Skill Efficiency Does Not Stack');
INSERT INTO skill (skill_name, skill_type, all_morale, efficiency, notes) VALUES ('Princess', 'hq', 0, 7, 'Skill Efficiency Does Not Stack');
INSERT INTO skill (skill_name, skill_type, all_morale, efficiency, notes) VALUES ('Integrity & Capability', 'hq', -0.05, 0, '-0.05 All Morale Per L.G.D. Operator');
INSERT INTO skill (skill_name, skill_type, efficiency) VALUES ('Backup Energy', 'power', 10);
INSERT INTO skill (skill_name, skill_type, efficiency) VALUES ('Heat Charge Alpha', 'power', 10);
INSERT INTO skill (skill_name, skill_type, efficiency) VALUES ('Equipment Maintenance', 'power', 15);
INSERT INTO skill (skill_name, skill_type, efficiency) VALUES ('Electrostatic Field', 'power', 20);
INSERT INTO skill (skill_name, skill_type, efficiency) VALUES ('Pulsed Arc Alpha', 'power', 10);
INSERT INTO skill (skill_name, skill_type, efficiency) VALUES ('Pulsed Arc Beta', 'power', 20);
INSERT INTO skill (skill_name, skill_type, efficiency) VALUES ('Superheat Charge', 'power', 15);
INSERT INTO skill (skill_name, skill_type, efficiency) VALUES ('Electromagnetic Charge Alpha', 'power', 10);
INSERT INTO skill (skill_name, skill_type, efficiency) VALUES ('Electromagnetic Charge Beta', 'power', 15);
INSERT INTO skill (skill_name, skill_type, metal_efficiency, record_efficiency, originium_efficiency, capacity, self_morale) VALUES ('Metalwork Alpha', 'factory', 30, 0, 0, 0, 0);
INSERT INTO skill (skill_name, skill_type, metal_efficiency, record_efficiency, originium_efficiency, capacity, self_morale) VALUES ('Metalwork Beta', 'factory', 35, 0, 0, 0, 0);
INSERT INTO skill (skill_name, skill_type, metal_efficiency, record_efficiency, originium_efficiency, capacity, self_morale) VALUES ('Combat Guidance Video', 'factory', 0, 30, 0, 0, 0);
INSERT INTO skill (skill_name, skill_type, metal_efficiency, record_efficiency, originium_efficiency, capacity, self_morale) VALUES ('Originium Work Alpha', 'factory', 0, 0, 30, 0, 0);
INSERT INTO skill (skill_name, skill_type, metal_efficiency, record_efficiency, originium_efficiency, capacity, self_morale) VALUES ('Originium Work Beta', 'factory', 0, 0, 35, 0, 0);
INSERT INTO skill (skill_name, skill_type, metal_efficiency, record_efficiency, originium_efficiency, capacity, self_morale) VALUES ('Warehouse Organization Alpha', 'factory', 10, 10, 10, 6, 0);
INSERT INTO skill (skill_name, skill_type, metal_efficiency, record_efficiency, originium_efficiency, capacity, self_morale) VALUES ('Warehouse Organization Beta', 'factory', 10, 10, 10, 10, 0);
INSERT INTO skill (skill_name, skill_type, metal_efficiency, record_efficiency, originium_efficiency, capacity, self_morale) VALUES ('Standardization Alpha', 'factory', 15, 15, 15, 0, 0);
INSERT INTO skill (skill_name, skill_type, metal_efficiency, record_efficiency, originium_efficiency, capacity, self_morale) VALUES ('Standardization Beta', 'factory', 25, 25, 25, 0, 0);
INSERT INTO skill (skill_name, skill_type, metal_efficiency, record_efficiency, originium_efficiency, capacity, self_morale, notes) VALUES ('Hothead', 'factory', 25, 25, 25, 0, 0, 'Starts At 20% Efficiency, Gain 1% Efficiency Per Hour Until Max');
INSERT INTO skill (skill_name, skill_type, metal_efficiency, record_efficiency, originium_efficiency, capacity, self_morale, notes) VALUES ('Slowcoach', 'factory', 25, 25, 25, 0, 0, 'Starts At 15% Efficiency, Gain 2% Efficiency Per Hour Until Max');
INSERT INTO skill (skill_name, skill_type, metal_efficiency, record_efficiency, originium_efficiency, capacity, self_morale, notes) VALUES ('Recycling', 'factory', 0, 0, 0, 0, 0, 'Gain 2% Efficiency per +1 Capacity From All Operators In Same Factory');
INSERT INTO skill (skill_name, skill_type, metal_efficiency, record_efficiency, originium_efficiency, capacity, self_morale) VALUES ('Troublemaker', 'factory', 25, 25, 25, -12, 0.2);
INSERT INTO skill (skill_name, skill_type, metal_efficiency, record_efficiency, originium_efficiency, capacity, self_morale) VALUES ('Junkman', 'factory', 0, 0, 0, 8, -0.25);
INSERT INTO skill (skill_name, skill_type, metal_efficiency, record_efficiency, originium_efficiency, capacity, self_morale) VALUES ('Geologist', 'factory', 0, 0, 35, 0, 0);
INSERT INTO skill (skill_name, skill_type, metal_efficiency, record_efficiency, originium_efficiency, capacity, self_morale) VALUES ('Rhine Tech Alpha', 'factory', 15, 15, 15, 0, 0);
INSERT INTO skill (skill_name, skill_type, metal_efficiency, record_efficiency, originium_efficiency, capacity, self_morale) VALUES ('Rhine Tech Beta', 'factory', 25, 25, 25, 0, 0);
INSERT INTO skill (skill_name, skill_type, metal_efficiency, record_efficiency, originium_efficiency, capacity, self_morale) VALUES ('Craftsmanship Spirit Alpha', 'factory', -5, -5, -5, 16, -0.15);
INSERT INTO skill (skill_name, skill_type, metal_efficiency, record_efficiency, originium_efficiency, capacity, self_morale) VALUES ('Craftsmanship Spirit Beta', 'factory', -5, -5, -5, 18, -0.25);
INSERT INTO skill (skill_name, skill_type, metal_efficiency, record_efficiency, originium_efficiency, capacity, self_morale) VALUES ('Boxing Guidance Video', 'factory', 0, 35, 0, 0, 0);
INSERT INTO skill (skill_name, skill_type, metal_efficiency, record_efficiency, originium_efficiency, capacity, self_morale) VALUES ('Meeboo: Manufacturing', 'factory', 30, 30, 30, 0, 0);
INSERT INTO skill (skill_name, skill_type, metal_efficiency, record_efficiency, originium_efficiency, capacity, self_morale) VALUES ('Volcanologist', 'factory', 0, 0, 35, 0, 0);
INSERT INTO skill (skill_name, skill_type, metal_efficiency, record_efficiency, originium_efficiency, capacity, self_morale) VALUES ('Originium Study', 'factory', 0, 0, 35, 0, 0);
INSERT INTO skill (skill_name, skill_type, metal_efficiency, record_efficiency, originium_efficiency, capacity, self_morale, notes) VALUES ('Team Spirit', 'factory', 0, 0, 0, 0, 0, "Ignores Morale Effects From Other Co-stationed Operators.");
INSERT INTO skill (skill_name, skill_type, metal_efficiency, record_efficiency, originium_efficiency, capacity, self_morale, notes) VALUES ('Originium Study', 'factory', 40, 40, 40, 0, 0, "Gain 5% Efficiency Per 5% Efficiency From Other Co-stationed Operators, Up To Max.");
INSERT INTO skill (skill_name, skill_type, efficiency, capacity, self_morale) VALUES ('Order Management Alpha', 'trade', 10, 1, 0);
INSERT INTO skill (skill_name, skill_type, efficiency, capacity, self_morale) VALUES ('Order Distribution Alpha', 'trade', 20, 0, 0);
INSERT INTO skill (skill_name, skill_type, efficiency, capacity, self_morale) VALUES ('Order Distribution Beta', 'trade', 30, 0, 0);
INSERT INTO skill (skill_name, skill_type, efficiency, capacity, self_morale) VALUES ('Negotiation', 'trade', 0, 3, -0.25);
INSERT INTO skill (skill_name, skill_type, efficiency, capacity, self_morale) VALUES ('Supply Management', 'trade', 25, 1, 0);
INSERT INTO skill (skill_name, skill_type, efficiency, capacity, self_morale) VALUES ('Communication', 'trade', 30, 0, -0.25);
INSERT INTO skill (skill_name, skill_type, efficiency, capacity, self_morale) VALUES ('Karlan Commercial Alpha', 'trade', 15, 1, 0);
INSERT INTO skill (skill_name, skill_type, efficiency, capacity, self_morale) VALUES ('Karlan Commercial Beta', 'trade', 15, 2, 0);
INSERT INTO skill (skill_name, skill_type, efficiency, capacity, self_morale) VALUES ('Penguin Logistics Alpha', 'trade', 20, 0, 0);
INSERT INTO skill (skill_name, skill_type, efficiency, capacity, self_morale) VALUES ('Penguin Logistics Beta', 'trade', 30, 0, 0);
INSERT INTO skill (skill_name, skill_type, efficiency, capacity, self_morale, notes) VALUES ('Feud', 'trade', 65, 0, 0.3,'When Stationed With Lappland');
INSERT INTO skill (skill_name, skill_type, efficiency, capacity, self_morale, notes) VALUES ('Tacit Understanding', 'trade', 0, 0, -0.3, 'When Stationed With Exusiai');
INSERT INTO skill (skill_name, skill_type, efficiency, capacity, self_morale, notes) VALUES ('Hidden Purpose Alpha', 'trade', 0, 2, -0.1, 'When Stationed With Texas');
INSERT INTO skill (skill_name, skill_type, efficiency, capacity, self_morale, notes) VALUES ('Hidden Purpose Beta', 'trade', 0, 4, -0.1, 'When Stationed With Texas');
INSERT INTO skill (skill_name, skill_type, efficiency, capacity, self_morale) VALUES ('Mission Guarantee', 'trade', 30, 1, 0);
INSERT INTO skill (skill_name, skill_type, efficiency, capacity, self_morale) VALUES ('Logistics Expert', 'trade', 35, 0, 0);
INSERT INTO skill (skill_name, skill_type, efficiency, capacity, self_morale) VALUES ('Lord of Karlan', 'trade', 20, 3, 0);
INSERT INTO skill (skill_name, skill_type, efficiency, capacity, self_morale) VALUES ('峯驰物流', 'trade', 20, 0, 0);
INSERT INTO skill (skill_name, skill_type, efficiency, capacity, self_morale) VALUES ('Young Master', 'trade', 30, 1, 0);
INSERT INTO skill (skill_name, skill_type, efficiency, clue_focus) VALUES ('Clue Search Alpha', 'reception', 10, 0);
INSERT INTO skill (skill_name, skill_type, efficiency, clue_focus) VALUES ('Clue Search Beta', 'reception',  20, 0);
INSERT INTO skill (skill_name, skill_type, efficiency, clue_focus) VALUES ('Divination', 'reception',  25, 0);
INSERT INTO skill (skill_name, skill_type, efficiency, clue_focus) VALUES ('Tracker', 'reception',  25, 0);
INSERT INTO skill (skill_name, skill_type, efficiency, clue_focus) VALUES ('Police Superintendent', 'reception',  25, 0);
INSERT INTO skill (skill_name, skill_type, efficiency, clue_focus) VALUES ('Astrology', 'reception',  25, 0);
INSERT INTO skill (skill_name, skill_type, efficiency, clue_focus) VALUES ('Watchman', 'reception',  10, 1);
INSERT INTO skill (skill_name, skill_type, efficiency, clue_focus) VALUES ('Messenger - Penguin Logistics', 10, 2);
INSERT INTO skill (skill_name, skill_type, efficiency, clue_focus) VALUES ('Liaison', 'reception',  10, 3);
INSERT INTO skill (skill_name, skill_type, efficiency, clue_focus) VALUES ('Counselor', 'reception',  10, 4);
INSERT INTO skill (skill_name, skill_type, efficiency, clue_focus) VALUES ('Arraigner', 'reception',  10, 5);
INSERT INTO skill (skill_name, skill_type, efficiency, clue_focus) VALUES ('Fallen Noble', 'reception',  10, 5);
INSERT INTO skill (skill_name, skill_type, efficiency, clue_focus) VALUES ('Courier', 'reception',  10, 6);
INSERT INTO skill (skill_name, skill_type, efficiency, clue_focus) VALUES ('Messenger', 'reception',  10, 7);
INSERT INTO skill (skill_name, skill_type, efficiency, clue_focus) VALUES ('Royal Detective (Self Proclaimed)', 'reception',  0, 2);
INSERT INTO skill (skill_name, skill_type, base_efficiency, elite_efficiency, skill_efficiency, chip_efficiency) VALUES ('Engineering', 'workshop', 70, 0, 0, 0);
INSERT INTO skill (skill_name, skill_type, base_efficiency, elite_efficiency, skill_efficiency, chip_efficiency) VALUES ('Nutriology', 'workshop', 0, 70, 0, 0);
INSERT INTO skill (skill_name, skill_type, base_efficiency, elite_efficiency, skill_efficiency, chip_efficiency) VALUES ('Tech Theory', 'workshop', 0, 0, 70, 0);
INSERT INTO skill (skill_name, skill_type, base_efficiency, elite_efficiency, skill_efficiency, chip_efficiency) VALUES ('Training Record', 'workshop', 0, 0, 0, 70);
INSERT INTO skill (skill_name, skill_type, base_efficiency, elite_efficiency, skill_efficiency, chip_efficiency) VALUES ('Pharmacology Alpha', 'workshop', 0, 75, 0, 0);
INSERT INTO skill (skill_name, skill_type, base_efficiency, elite_efficiency, skill_efficiency, chip_efficiency) VALUES ('Pharmacology Beta', 'workshop', 0, 80, 0, 0);
INSERT INTO skill (skill_name, skill_type, base_efficiency, elite_efficiency, skill_efficiency, chip_efficiency) VALUES ('Toxicology Alpha', 'workshop', 0, 75, 0, 0);
INSERT INTO skill (skill_name, skill_type, base_efficiency, elite_efficiency, skill_efficiency, chip_efficiency) VALUES ('Toxicology Beta', 'workshop', 0, 80, 0, 0);
INSERT INTO skill (skill_name, skill_type, base_efficiency, elite_efficiency, skill_efficiency, chip_efficiency) VALUES ('Scholar', 'workshop', 0, 80, 0, 0);
INSERT INTO skill (skill_name, skill_type, base_efficiency, elite_efficiency, skill_efficiency, chip_efficiency) VALUES ('Blasting Materialogy Alpha', 'workshop', 0, 75, 0, 0);
INSERT INTO skill (skill_name, skill_type, base_efficiency, elite_efficiency, skill_efficiency, chip_efficiency) VALUES ('Blasting Materialogy Beta', 'workshop', 0, 80, 0, 0);
INSERT INTO skill (skill_name, skill_type, base_efficiency, elite_efficiency, skill_efficiency, chip_efficiency) VALUES ('Arts of War', 'workshop', 0, 0, 80, 0);
INSERT INTO skill (skill_name, skill_type, base_efficiency, elite_efficiency, skill_efficiency, chip_efficiency) VALUES ('Focus Alpha', 'workshop', 40, 40, 40, 40);
INSERT INTO skill (skill_name, skill_type, base_efficiency, elite_efficiency, skill_efficiency, chip_efficiency) VALUES ('Focus Beta', 'workshop', 60, 60, 60, 60);
INSERT INTO skill (skill_name, skill_type, base_efficiency, elite_efficiency, skill_efficiency, chip_efficiency) VALUES ('Skillful Craftsman', 'workshop', 50, 50, 50, 50);
INSERT INTO skill (skill_name, skill_type, base_efficiency, elite_efficiency, skill_efficiency, chip_efficiency) VALUES ('Meeboo: Processing', 'workshop', 65, 65, 65, 65);
INSERT INTO skill (skill_name, skill_type, base_efficiency, elite_efficiency, skill_efficiency, chip_efficiency) VALUES ('Arise', 'workshop', 0, 0, 80, 0);
INSERT INTO skill (skill_name, skill_type, base_efficiency, elite_efficiency, skill_efficiency, chip_efficiency) VALUES ('Multifunctional Robotter', 'workshop', 50, 50, 50, 50);
INSERT INTO skill (skill_name, skill_type, base_efficiency, elite_efficiency, skill_efficiency, chip_efficiency, notes) VALUES ('Drone - Soaring Dragon', 'workshop', 0, 0, 0, 0, '-2 Morale Used For All >=4 Morale Recipes');
INSERT INTO skill (skill_name, skill_type, efficiency) VALUES ('Personnel Management Alpha', 'office', 20);
INSERT INTO skill (skill_name, skill_type, efficiency) VALUES ('Catastrophe Messenger Alpha', 'office', 30);
INSERT INTO skill (skill_name, skill_type, efficiency) VALUES ('Catastrophe Messenger Beta', 'office', 45);
INSERT INTO skill (skill_name, skill_type, efficiency) VALUES ('Psychology', 'office', 40);
INSERT INTO skill (skill_name, skill_type, efficiency) VALUES ('WRITER', 'office', 40);
INSERT INTO skill (skill_name, skill_type, guard, medic, vanguard, caster, sniper, defender, supporter, specialist) VALUES ('Drillmaster', 'training', 25, 25, 25, 25, 25, 25, 25, 25);
INSERT INTO skill (skill_name, skill_type, guard, medic, vanguard, caster, sniper, defender, supporter, specialist) VALUES ('Guard Expert Alpha', 'training', 30, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO skill (skill_name, skill_type, guard, medic, vanguard, caster, sniper, defender, supporter, specialist) VALUES ('Guard Expert Beta', 'training', 50, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO skill (skill_name, skill_type, guard, medic, vanguard, caster, sniper, defender, supporter, specialist) VALUES ('Medic Expert Alpha', 'training', 0, 30, 0, 0, 0, 0, 0, 0);
INSERT INTO skill (skill_name, skill_type, guard, medic, vanguard, caster, sniper, defender, supporter, specialist) VALUES ('Medic Expert Beta', 'training', 0, 50, 0, 0, 0, 0, 0, 0);
INSERT INTO skill (skill_name, skill_type, guard, medic, vanguard, caster, sniper, defender, supporter, specialist) VALUES ('Vanguard Expert Alpha', 'training', 0, 0, 30, 0, 0, 0, 0, 0);
INSERT INTO skill (skill_name, skill_type, guard, medic, vanguard, caster, sniper, defender, supporter, specialist) VALUES ('Vanguard Expert Beta', 'training', 0, 0, 50, 0, 0, 0, 0, 0);
INSERT INTO skill (skill_name, skill_type, guard, medic, vanguard, caster, sniper, defender, supporter, specialist) VALUES ('Caster Expert Alpha', 'training', 0, 0, 0, 30, 0, 0, 0, 0);
INSERT INTO skill (skill_name, skill_type, guard, medic, vanguard, caster, sniper, defender, supporter, specialist) VALUES ('Caster Expert Beta', 'training', 0, 0, 0, 50, 0, 0, 0, 0);
INSERT INTO skill (skill_name, skill_type, guard, medic, vanguard, caster, sniper, defender, supporter, specialist) VALUES ('Sniper Expert Alpha', 'training', 0, 0, 0, 0, 30, 0, 0, 0);
INSERT INTO skill (skill_name, skill_type, guard, medic, vanguard, caster, sniper, defender, supporter, specialist) VALUES ('Sniper Expert Beta', 'training', 0, 0, 0, 0, 50, 0, 0, 0);
INSERT INTO skill (skill_name, skill_type, guard, medic, vanguard, caster, sniper, defender, supporter, specialist) VALUES ('Black Arrow', 'training', 0, 0, 0, 0, 60, 0, 0, 0);
INSERT INTO skill (skill_name, skill_type, guard, medic, vanguard, caster, sniper, defender, supporter, specialist) VALUES ('Defender Expert Alpha', 'training', 0, 0, 0, 0, 0, 30, 0, 0);
INSERT INTO skill (skill_name, skill_type, guard, medic, vanguard, caster, sniper, defender, supporter, specialist) VALUES ('Defender Expert Beta', 'training', 0, 0, 0, 0, 0, 50, 0, 0);
INSERT INTO skill (skill_name, skill_type, guard, medic, vanguard, caster, sniper, defender, supporter, specialist) VALUES ('Hannya', 'training', 0, 0, 0, 0, 0, 60, 0, 0);
INSERT INTO skill (skill_name, skill_type, guard, medic, vanguard, caster, sniper, defender, supporter, specialist) VALUES ('Supporter Expert Alpha', 'training', 0, 0, 0, 0, 0, 0, 30, 0);
INSERT INTO skill (skill_name, skill_type, guard, medic, vanguard, caster, sniper, defender, supporter, specialist) VALUES ('Supporter Expert Beta', 'training', 0, 0, 0, 0, 0, 0, 50, 0);
INSERT INTO skill (skill_name, skill_type, guard, medic, vanguard, caster, sniper, defender, supporter, specialist) VALUES ('Specialist Expert Alpha', 'training', 0, 0, 0, 0, 0, 0, 0, 30);
INSERT INTO skill (skill_name, skill_type, guard, medic, vanguard, caster, sniper, defender, supporter, specialist) VALUES ('Specialist Expert Beta', 'training', 0, 0, 0, 0, 0, 0, 0, 30);
INSERT INTO skill (skill_name, skill_type, self_morale, random_morale, all_morale) VALUES ('Release', 'dorm', 0.55, 0, 0);
INSERT INTO skill (skill_name, skill_type, self_morale, random_morale, all_morale) VALUES ('Solitude', 'dorm', 0.7, 0, 0);
INSERT INTO skill (skill_name, skill_type, self_morale, random_morale, all_morale) VALUES ('Concealed Gourmet', 'dorm', 0.75, 0, 0);
INSERT INTO skill (skill_name, skill_type, self_morale, random_morale, all_morale) VALUES ('Craze', 'dorm', 0.85, 0, 0);
INSERT INTO skill (skill_name, skill_type, self_morale, random_morale, all_morale) VALUES ('Elegy', 'dorm', 1, 0, 0);
INSERT INTO skill (skill_name, skill_type, self_morale, random_morale, all_morale) VALUES ('Thoughtfulness', 'dorm', 0, 0.55, 0);
INSERT INTO skill (skill_name, skill_type, self_morale, random_morale, all_morale) VALUES ('Medical Service', 'dorm', 0, 0.65, 0);
INSERT INTO skill (skill_name, skill_type, self_morale, random_morale, all_morale) VALUES ('Mercy', 'dorm', 0, 0.75, 0);
INSERT INTO skill (skill_name, skill_type, self_morale, random_morale, all_morale) VALUES ('Break Loose', 'dorm', 0, 0, 0.1);
INSERT INTO skill (skill_name, skill_type, self_morale, random_morale, all_morale) VALUES ('Absolution', 'dorm', 0.55, 0, 0.1);
INSERT INTO skill (skill_name, skill_type, self_morale, random_morale, all_morale) VALUES ('Inspiration', 'dorm', 0, 0, 0.1);
INSERT INTO skill (skill_name, skill_type, self_morale, random_morale, all_morale) VALUES ('Idol', 'dorm', 0, 0, 0.15);
INSERT INTO skill (skill_name, skill_type, self_morale, random_morale, all_morale) VALUES ('Violin Solo', 'dorm', 0, 0, 0.15);
INSERT INTO skill (skill_name, skill_type, self_morale, random_morale, all_morale) VALUES ('Leader', 'dorm', 0, 0, 0.15);
INSERT INTO skill (skill_name, skill_type, self_morale, random_morale, all_morale) VALUES ('General Zima', 'dorm', 0, 0, 0.2);
INSERT INTO skill (skill_name, skill_type, self_morale, random_morale, all_morale) VALUES ('Lionheart', 'dorm', 0, 0, 0.2);
INSERT INTO skill (skill_name, skill_type, self_morale, random_morale, all_morale) VALUES ('Lady of the Lamp', 'dorm', 0, 0, 0.2);
INSERT INTO skill (skill_name, skill_type, self_morale, random_morale, all_morale) VALUES ('Liveliness', 'dorm', 0.4, 0.2, 0);
INSERT INTO skill (skill_name, skill_type, self_morale, random_morale, all_morale) VALUES (E'Explorer\'s Passion', 'dorm', 0.5, 0.25, 0);
INSERT INTO skill (skill_name, skill_type, self_morale, random_morale, all_morale) VALUES ('Baking', 'dorm', 0.3, 0.3, 0);
INSERT INTO skill (skill_name, skill_type, self_morale, random_morale, all_morale) VALUES ('Cooking', 'dorm', 0.35, 0.35, 0);
INSERT INTO skill (skill_name, skill_type, self_morale, random_morale, all_morale) VALUES ('Harmonious', 'dorm', 0.2, 0.4, 0);
INSERT INTO skill (skill_name, skill_type, self_morale, random_morale, all_morale) VALUES ('Radiant Knight', 'dorm', 0.25, 0.5, 0);
INSERT INTO skill (skill_name, skill_type, self_morale, random_morale, all_morale) VALUES ('Karlan Saint', 'dorm', 0.25, 0.5, 0);
INSERT INTO skill (skill_name, skill_type, self_morale, random_morale, all_morale) VALUES ('Laziness', 'dorm', -0.1, 0, 0.2);
INSERT INTO skill (skill_name, skill_type, self_morale, random_morale, all_morale) VALUES ('Sleepiness', 'dorm', -0.1, 0, 0.25);
INSERT INTO skill (skill_name, skill_type, self_morale, random_morale, all_morale, notes) VALUES ('Make Tea', 'dorm', 0, 0.55, 0, 'If target is Ceylon, random_morale is 1 instead.');
