INSERT INTO dorm VALUES ('No Skill', 0, 0, 0);
INSERT INTO dorm VALUES ('Solitude', 0.7, 0, 0);
INSERT INTO dorm VALUES ('Craze', 0.85, 0, 0);
INSERT INTO dorm VALUES ('Elegy', 1, 0, 0);
INSERT INTO dorm VALUES ('Thoughtfulness', 0, 0.55, 0);
INSERT INTO dorm VALUES ('Medical Service', 0, 0.65, 0);
INSERT INTO dorm VALUES ('Mercy', 0, 0.75, 0);
INSERT INTO dorm VALUES ('Inspiration', 0, 0, 0.1);
INSERT INTO dorm VALUES ('Idol', 0, 0, 0.15);
INSERT INTO dorm VALUES ('Violin Solo', 0, 0, 0.15);
INSERT INTO dorm VALUES ('Leader', 0, 0, 0.15);
INSERT INTO dorm VALUES ('General Zima', 0, 0, 0.2);
INSERT INTO dorm VALUES ('Lionheart', 0, 0, 0.2);
INSERT INTO dorm VALUES ('Lady of the Lamp', 0, 0, 0.2);
INSERT INTO dorm VALUES ('Liveliness', 0.4, 0.2, 0);
INSERT INTO dorm VALUES (E'Explorer\'s Passion', 0.5, 0.25, 0);
INSERT INTO dorm VALUES ('Baking', 0.3, 0.3, 0);
INSERT INTO dorm VALUES ('Cooking', 0.35, 0.35, 0);
INSERT INTO dorm VALUES ('Harmonious', 0.2, 0.4, 0);
INSERT INTO dorm VALUES ('Radiant Knight', 0.25, 0.5, 0);
INSERT INTO dorm VALUES ('Karlan Saint', 0.25, 0.5, 0);
INSERT INTO dorm VALUES ('Laziness', -0.1, 0, 0.2);
INSERT INTO dorm VALUES ('Sleepiness', -0.1, 0, 0.25);